trigger:
  - main # ou la branche de votre choix

jobs:
- job: TestKeyVaultAccess
  pool:
    vmImage: 'ubuntu-latest' # ou un autre agent de votre choix
  steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'AzureKeyVaultConnection' # Remplacez par le nom de votre connexion de service
      KeyVaultName: 'KeyVaultPremierProjet ' # Remplacez par le nom de votre Key Vault
      SecretsFilter: '*' # Vous pouvez spécifier des secrets spécifiques ou utiliser '*' pour tous
      RunAsPreJob: false

